name:                aoc2015
version:             0.1.0.0
github:              "falcowinkler/adventofcode"
license:             BSD3
author:              "Falco Winkler"
maintainer:          "example@example.com"
copyright:           "2023 Falco Winkler"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/aoc2015#readme>

dependencies:
- base >= 4.7 && < 5
- containers
- parsec
- cryptonite
- utf8-string
- split

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints
- -Wno-missing-signatures

library:
  source-dirs: src
  dependencies:
    - parsec
    - containers
    - cryptonite
    - bytestring
    - utf8-string
    - split

executables:
  aoc2015-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aoc2015

tests:
  aoc2015-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aoc2015
    - hspec
    - hspec-discover
